### ISSUE TITLE
Add alternate inventory functionality

### ISSUE THREAD

**Issue by DonaldTsang** [adriantache/Big-Five-Personality-Test#4]
https://ipip.ori.org/newMultipleconstructs.htm has multiple inventories, where Johnson (2014) and Maples (2014) both have bigger details than the current 50-item test. Is it possible to implement those as well for completeness sake?

**Comment by adriantache** [comment]
If you have a non-copyrighted version of those 120-item tests it would certainly be possible to add them, and interesting to code too! Also, if there is anything I need to know about them, like different scoring methodologies or whatever, please let me know!

**Comment by DonaldTsang** [comment]
@adriantache most of the tests in the link provided are not copyrighted (I think, since they are available to the public).

**Comment by adriantache** [comment]
Can you please send me a direct link to the test questions and the answer keys for each of those tests? The IPIP website should be public domain though, so if you find them there that should work.

**Comment by DonaldTsang** [comment]
Here is a basic list of all the ones noted in another set of repos by Alheimsins
- [x] https://github.com/Alheimsins/b5-50-ipip-neo-pi-r
  - [x] https://github.com/Alheimsins/b5-50-ipip-neo-pi-r/issues/29
  - [x] https://github.com/Alheimsins/b5-50-ipip-neo-pi-r/issues/30
  - [x] https://github.com/Alheimsins/b5-50-ipip-neo-pi-r/issues/31
- [x] https://github.com/Alheimsins/b5-johnson-120-ipip-neo-pi-r
  - [x] https://github.com/Alheimsins/b5-johnson-120-ipip-neo-pi-r/issues/87
- [x] https://github.com/Alheimsins/b5-costa-mccrae-300-ipip-neo-pi-r

**Comment by adriantache** [comment]
https://github.com/adriantache/Big-Five-Personality-Test/commit/4cbe699b620a06dee2fb072fb14642b5153e6df3 Completely rewrote app and added the three main tests. I'll make some JSON files out of the other ones you linked above and add them too eventually.

**Comment by adriantache** [comment]
1c6f43f226e11fe76bd349b8880946762dcdaaf9 and 2f06391d3b8572993b9a59d9ef4ea16f32b21c76 Added the nameless 50 and 100 item tests as well.
