### ISSUE TITLE
How to create the same type of quiz?

### ISSUE THREAD

**Issue by nurlan-dzhavadov** [adriantache/Big-Five-Personality-Test#5]
Hello!
Thank you for your app! I've downloaded it and it's amazing!
I have an issue. I want to add a personality quiz to my app, so not the one that has right or wrong answers and I want it to have different results depending on what answers you chose (there should be 4 questions). Do you know how can I do that?
P.S. I understand that you have code for your app, but I'm new to coding and it's difficult for me to understand it all.

Thank you!

**Comment by adriantache** [comment]
Well, you can simply have a ConstraintLayout in which you add four RadioGroups with the description of the question and inside the RadioGroup you add RadioButtons. And then you just set an OnClickListener on each RadioGroup that adds the score of the button they clicked to your main score, which you then display in a TextView. I can't imagine it being simpler than that.

**Comment by nurlan-dzhavadov** [comment]
Thank you!
